# Generated by Django 4.1.7 on 2023-04-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Image',
            field=models.ImageField(default='image', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
